services:
  order-api:
    build:
      context: .
      dockerfile: OrderApi/Docker/Dockerfile
    ports:
      - "5001:8080"
      - "5002:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    volumes:
      - ./certs:/https:ro
    depends_on:
      - product-api
  product-api:
    build:
      context: .
      dockerfile: ProductApi/Docker/Dockerfile
    ports:
      - "5003:8080"
      - "5004:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
    volumes:
      - ./certs:/https:ro

networks:
  default:
    name: microservices-network